baseurl = "https://rogerjbos.com/"
languageCode = "en-us"
title = "ETF Ranking System"
#theme = "ghostwriter"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Investing"
    url = "/investing/"
    weight = 3
[[menu.main]]
    name = "Linux"
    url = "/linux/"
    weight = 4

[params]
    description = "ETF Ranking System"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

