baseurl = "https://ranks.rogerjbos.com/rankings/"
languageCode = "en-us"
theme = "ghostwriter"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "2019 Roger J. Bos, CFA"

[Params]
    mainSections = ["/"]
    intro = true

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
    
[[menu.main]]
    name = "ETF Index"
    url = "/"
    weight = 2
